"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'False'

# Allowed hosts - replace with your domain or server IP
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

# Browser-side protections
SECURE_BROWSER_XSS_FILTER = True  # Helps protect against cross-site scripting attacks

X_FRAME_OPTIONS = 'DENY'  # Prevents your site from being embedded in iframes

SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevents MIME type sniffing by browsers

# Enforce HTTPS
CSRF_COOKIE_SECURE = True  # Ensures CSRF cookies are only sent over HTTPS

SESSION_COOKIE_SECURE = True  # Ensures session cookies are only sent over HTTPS

# CSP configurations
CSP_DEFAULT_SRC = ("'self'",)  # Only allow resources from this site


# SECURITY SETTINGS FOR HTTPS AND SECURE COOKIES

# SECURE_SSL_REDIRECT: This setting ensures that all non-HTTPS requests are redirected to HTTPS.
SECURE_SSL_REDIRECT = True #Set it to True to enforce HTTPS.

# SECURE_HSTS_SECONDS: This setting tells browsers to only access the site via HTTPS for the specified number of seconds. It's a strong security measure.
SECURE_HSTS_SECONDS = 31536000 # (one year) to enforce the use of HTTPS for a long period.

# ECURE_HSTS_INCLUDE_SUBDOMAINS: When this is set to True, all subdomains of your site will also be forced to use HTTPS.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD: Set this to True if you want your domain to be eligible for the HTTP Strict Transport Security (HSTS) preload list.
# Important: Only set this to True if you are absolutely sure that you want to use HSTS and you have configured it correctly for all your subdomains.
SECURE_HSTS_PRELOAD = True

# Cookies security
SESSION_COOKIE_SECURE = True  # Send session cookies only over HTTPS
CSRF_COOKIE_SECURE = True  # Send CSRF cookies only over HTTPS

# Additional security headers
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking by denying iframe embedding
# TTP_X_FORWARDED_PROTO: This is the header added by your proxy (e.g., Nginx, Apache, or a load balancer) to indicate the original protocol (http or https) used by the client.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') # ["SECURE_PROXY_SSL_HEADER", "HTTP_X_FORWARDED_PROTO"]
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable browser's XSS protection



# Application definition

INSTALLED_APPS = [
    'bookshelf.apps.BookshelfConfig',
    'relationship_app.apps.RelationshipAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

# Content Security Policy settings for development
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "http://localhost:8000", "http://127.0.0.1:8000")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "http://localhost:8000", "http://127.0.0.1:8000")
CSP_IMG_SRC = ("'self'", "data:")
CSP_FONT_SRC = ("'self'", "data:")
CSP_CONNECT_SRC = ("'self'", "ws://localhost:8000")  # Allow WebSocket connections
CSP_FRAME_SRC = ("'self'",)

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Add custom template directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Enforce a minimum password length
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Login and logout redirection
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
