# Generated by Django 5.1.3 on 2024-11-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
